### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by charles-huet-ixxi** [asmaloney/asmCrashReport#16]
Hi,

there is no licensing information in the repository, meaning that [this is not useable freely as default copyright laws apply](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license).

Could you please add a license to the project ?

Thanks

**Comment by albesze** [comment]
Supporting this.

I would like to use this project as well for my project, but I cannot since it lacks a license.  I hope I don't have to reimplement this project.

May I suggest a short and permissive license such as the MIT license?

**Comment by asmaloney** [comment]
@albesze "bribe" not necessary, but very much appreciated 😆 Thanks.

**Comment by albesze** [comment]
@asmaloney Even if you didn't or refused, I would still have considered it money well spent, considering how much time I spend trying to solve this very problem.

Also, I discovered your comment on the crash report blog post after the fact.  If I bothered reading your comment replies, it would have saved me some time.
